### ISSUE TITLE
Create & publish an npm package

### ISSUE THREAD

**Issue by jdhollis** [NuID/zk#1]
Looking at integration with Rails (which uses [Webpacker](https://github.com/rails/webpacker) by default for managing JavaScript dependencies), it would be much simpler for people if we had a published release of `zk`.

In the short term, I'm just going to do my own manual build and include it straight in the repository.

I'm curious to see how it's going to behave with ES6-style includes.

**Comment by usernolan** [comment]
@jdhollis I've been looking into packaging this up, and one of the changes I made recently will cause the JS example in the README to fail. I've fixed that and have been looking into the best options for bundling it up via NPM. Will keep you updated.

**Comment by jdhollis** [comment]
The main thing to keep an eye on is whether it’ll also work in a browser context (given the riot of module standards there).

**Comment by jdhollis** [comment]
This might help: https://webpack.js.org/concepts/modules/

**Comment by usernolan** [comment]
The issue we run into is idiosyncrasy between JS and CLJS. The more advanced CLJS we write (`defmulti`, `defrecord`, etc.), the more awkward the API is in JS (or the more work it requires to expose the API appropriately). Have been evaluating the trade-offs throughout the afternoon, still thinking on it and getting closer to something workable.

**Comment by usernolan** [comment]
Once the JS API gets ironed out, `shadow-cljs` has facilities to define output module and import statement type/style. I imagine there is a decent release script to be written that outputs and uploads an NPM package supports both node and the browser. I may be overly optimistic...

**Comment by usernolan** [comment]
`npm publish` workflow added in https://github.com/NuID/zk/commit/5051761db3c5ee3b85e8bf834ab3dd330394e720.

packages live [here](https://www.npmjs.com/settings/nuid/packages) and are private for now.
