### ISSUE TITLE
TypeScript typings?

### ISSUE THREAD

**Issue by prescience-data** [NuID/zk#11]
Is it on the roadmap to export typings with the package?

Currently having to attempt to figure out the shapes for manual implementation without any JS source to follow is tricky.

**Comment by localshred** [comment]
Hi @prescience-data, we appreciate you reaching out on this issue!

I'm investigating adding type declarations to the zk npm package today. In the meantime you can reference the [package documentation](https://portal.nuid.io/docs/client/web#docs) on our developer portal. I'll keep this issue updated as to my progress.

**Comment by localshred** [comment]
@prescience-data this has been released under v0.1.2. Please try it out and let us know if you have any issues or other questions. Happy hacking!
